"type" = "yellow"
"constant" = "fg"
"constant.builtin" = { fg = "purple", modifiers = ["italic"] }
"constant.builtin.boolean" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "green"
"string" = "aqua"
"string.regexp" = "green"
"string.special" = "yellow"
"comment" = { fg = "grey1", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = { fg = "purple", modifiers = ["italic"] }
"variable.parameter" = "fg"
"variable.other.member" = "blue"
"label" = "orange"
"punctuation" = "grey2"
"punctuation.delimiter" = "grey1"
"punctuation.bracket" = "fg"
"punctuation.special" = "blue"
"keyword" = "red"
"keyword.operator" = "orange"
"keyword.directive" = "purple"
"keyword.storage" = "red"
"operator" = "orange"
"function" = "green"
"function.macro" = "green"
"tag" = "orange"
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"attribute" = { fg = "purple", modifiers = ["italic"] }
"constructor" = "green"
"module" = "yellow"
"special" = "blue"

"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

"ui.background" = {}
"ui.background.separator" = "bg_visual"
"ui.cursor" = { fg = "bg1", bg = "grey2" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey1" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.cursor.match" = { fg = "orange", bg = "bg_yellow" }
"ui.cursor.primary" = { fg = "bg0", bg = "fg" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg2" }
"ui.selection" = { bg = "bg3" }
"ui.linenr" = "grey0"
"ui.linenr.selected" = "grey2"
"ui.statusline" = { fg = "fg", bg = "bg2" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "bg0", bg = "statusline2", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.bufferline" = { fg = "grey2", bg = "bg3" }
"ui.bufferline.active" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.popup" = { fg = "grey2", bg = "bg0" }
"ui.window" = { fg = "bg4", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.menu" = { fg = "fg", bg = "bg0" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }

"hint" = "green"
"info" = "blue"
"warning" = "yellow"
"error" = "red"

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]

bg_dim = "#1E2326"
bg0 = "#272E33"
bg1 = "#2E383C"
bg2 = "#374145"
bg3 = "#414B50"
bg4 = "#495156"
bg5 = "#4F5B58"
bg_visual = "#493B40"
bg_red = "#4C3743"
bg_green = "#3C4841"
bg_blue = "#384B55"
bg_yellow = "#45443C"

fg = "#D3C6AA"
red = "#E67E80"
orange = "#E69875"
yellow = "#DBBC7F"
green = "#A7C080"
aqua = "#83C092"
blue = "#7FBBB3"
purple = "#D699B6"

grey0 = "#7A8478"
grey1 = "#859289"
grey2 = "#9DA9A0"

statusline1 = "#A7C080"
statusline2 = "#D3C6AA"
statusline3 = "#E67E80"
